config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "homepages#index"

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :hotels
  resources :rooms
  resources :bookings do 
    member do 
      post 'checkout', to: 'payments#checkout'
    end
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
    @hotels = Hotel.all
  end
end

app/views/homepages/index.html.erb
<h2 class="heading">Hotels</h2>
<% if @hotels.any? %>
  <div class="hotel-list">
    <% @hotels.each do |hotel| %>
      <div class="hotel-card">
        <% if hotel.image.attached? %> 
          <img src="<%= url_for(hotel.image) %>" alt="<%= hotel.name %>" class="hotel-image">
        <% end %>
        <div class="hotel-info">
          <h3 class="hotel-name"><%= hotel.name %></h3>
          <p class="hotel-address"><%= hotel.address %></p>
          <p class="hotel-description"><%= truncate(hotel.description, length: 100) %></p>
          <p class="hotel-rating">Rating: <%= hotel.rating %>/5</p>
          <p class="hotel-contact">Contact: <%= hotel.number %></p>
          <%= link_to "View Details", room_path(hotel), class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="no-hotels">No Hotels available.</p>
<% end %>