config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "homepages#index"

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :hotels
  resources :rooms
  resources :bookings do 
    member do 
      post 'checkout', to: 'payments#checkout'
    end
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_one_attached :image
  has_many :rooms , dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :address, presence: true, length: { maximum: 255 }
  validates :number, presence: true, format: { with: /\A\d{10}\z/, message: "must be a 10-digit number" }
  validates :description, presence: true, length: { maximum: 250 }
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  def hotel_names
    "#{name}"
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  
  before_action :get_hotel , only: [:edit, :update, :destroy]

  before_action :list_all_hotels, only: [:index, :edit]

  def index 
  end

  def new 
    @hotel = Hotel.new
  end

  def create 
    @hotel = Hotel.new(hotel_params)
    if @hotel.save 
      flash[:notice] = 'Hotel information was successfully create.'
      redirect_to hotels_path(@hotel)
    else
      render :new
    end
  end

  def edit 
  end

  def update
    if @hotel.update(hotel_params)
      flash[:notice] = 'Hotel information was succesfully updadte.'
      redirect_to hotels_path(@hotel)
    else
      render :edit
    end
  end

  def destroy
    if @hotel.destroy
      flash[:notice] = 'Hotel was successfully deleted.'
      redirect_to hotels_path(@hotel)
    else
      flash[:alert] = 'Hotel was not deleted.'
    end
  end
  
  private

  def list_all_hotels
    @hotels = Hotel.all
  end

  def get_hotel
    @hotel = Hotel.find(params[:id])
  end

  def hotel_params
    params.require(:hotel).permit(:name, :address, :number, :description, :rating, :image)
  end
end

app/views/hotels/_form.html.erb
<%= form_with model: @hotel do |form| %>
<% if @hotel.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this booking from being saved:</h2>
    <ul>
      <% @hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
  <div class="col-lg-4">
    <div class="form-group">
      <%= form.label :name, class: 'mb-2' %>
      <%= form.text_field :name, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
      <%= form.label :address, class: 'mb-2' %>
      <%= form.text_field :address, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-4">
    <div class="form-group">
      <%= form.label :number, class: 'mb-2' %>
      <%= form.text_field :number, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
      <%= form.label :description, class: 'mb-2' %>
      <%= form.text_field :description, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-4">
    <div class="form-group">
      <%= form.label :rating, class: 'mb-2' %>
      <%= form.text_field :rating, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
</div>
<div class="row">
  <div class="col-lg-12 mt-4">
    <%= form.submit class: 'btn btn-primary btn-lg rounded-0' %>
    <%= link_to "Hotel list", hotels_path, class: "btn btn-outline-primary btn-lg rounded-0"%>
  </div>
</div>
<% end %>

app/views/hotels/edit.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-4 mb-4">
    <div class="card-body">
      <h2 class="text-center">Update Hotel Information</h2>
    </div>
  </div>
  <%= render 'form', hotel: @hotel %>
</div>

app/views/hotels/index.html.erb
<%= link_to "Add New Hotel", new_hotel_path, class: "btn btn-primary btn-lg mb-4 rounded-0" %>
<%= link_to "Home", root_path, class: "btn btn-primary btn-lg mb-4 rounded-0" %>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Contect_number</th>
        <th>description</th>
        <th>rating</th> 
        <th>image</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @hotels.each do |hotel| %>
        <tr>
          <td><%= hotel.name %></td>
          <td><%= hotel.address %></td>
          <td><%= hotel.number %></td>
          <td><%= hotel.description %></td>
          <td><%= hotel.rating %></td>
          <td>
            <% if hotel.image.attached? %>
              <%= image_tag hotel.image ,size: "100x100", class: "img-thumbnail"%>
            <% else %>
              <p>No image available</p>
            <% end %>
          </td>
          <td><%= link_to "Edit", edit_hotel_path(hotel), class: "btn btn-primary" %></th>
          <td><%= button_to "Delete", hotel, method: :delete, class:"btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/hotels/new.html.erb
<div class="col-lg-12">
<div class="card rounded-0 mt-4 mb-4">
  <div class="card-body">
    <h2 class="text-center">Add Hotel Information</h2>
  </div>
</div>
<%= render 'form', hotel: @hotel %>